name: codigo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_slidable: ^4.0.0
  supabase_flutter: ^2.8.4
  shared_preferences: ^2.5.2
  video_player: ^2.7.2
  video_player_web: ^2.3.4
  video_player_win: ^3.1.1
  table_calendar: ^3.1.3

  # Fix intl version issue
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true # Enables localization file generation

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

  assets:
    - assets/profile_placeholder.png

